In [1]:
import numpy as np
from sklearn import preprocessing


data = [[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]

encoder = preprocessing.OneHotEncoder()
encoder.fit(data)
encoder.transform([[0, 1, 3]]).toarray()
encoded_vector = encoder.transform([[0, 1, 3]]).toarray()
print(encoded_vector.shape)
# (1, 9)
print(encoded_vector)
# [[1. 0. 0. 1. 0. 0. 0. 0. 1.]]

(1, 9)
[[1. 0. 0. 1. 0. 0. 0. 0. 1.]]


# 有3列 每列为一个特征:
|     |     |     |
| --- | --- | --- |
| 0   | 0   | 3   |
| 1   | 1   | 0   |
| 0   | 2   | 1   |
| 1   | 0   | 2   |

- 第一列的取值范围是 {0, 1}
- 第二列的取值范围是 {0, 1, 2}
- 第三列的取值范围是 {0, 1, 2, 3}
所以对应的 0 1 3 的 one-hot 编码为 10   010  0001

In [ ]:
# If you want to encode the data in a way that any category is not missing, you can set the parameter handle_unknown='ignore' when creating the OneHotEncoder object. This will add a new column to the right of the matrix, which will be marked as 1 for any category that was not seen during the fit process.
data = np.array([[0, 2, 1, 12], [1, 3, 5, 3], [2, 3, 2, 12], [1, 2, 4, 3]])

encoder = preprocessing.OneHotEncoder()
encoder.fit(data)
encoded_vector = encoder.transform([[2, 3, 5, 3]]).toarray()
print(encoded_vector.shape)
print(encoded_vector)

(1, 11)
[[0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]
